Load active_support/core_ext/integer explicitly to avoid ActiveModel's error
 ```
 An error occurred while loading ./spec/rbs_activemodel/active_model_spec.rb.
 Failure/Error:
   MIXINS = [::ActiveModel::Model, ::ActiveModel::Attributes,
             ::ActiveModel::SecurePassword, ::ActiveModel::Validations].freeze #: Array[Module]

 NoMethodError:
   undefined method 'minutes' for an instance of Integer
 # ./lib/rbs_activemodel/active_model.rb:26:in '<class:Generator>'
 # ./lib/rbs_activemodel/active_model.rb:24:in '<module:ActiveModel>'
 # ./lib/rbs_activemodel/active_model.rb:10:in '<module:RbsActivemodel>'
 # ./lib/rbs_activemodel/active_model.rb:9:in '<top (required)>'
 # ./lib/rbs_activemodel.rb:3:in 'Kernel#require_relative'
 # ./lib/rbs_activemodel.rb:3:in '<top (required)>'
 # ./spec/rbs_activemodel/active_model_spec.rb:5:in '<top (required)>'
 No examples found.
 ```